### ISSUE TITLE
Recursos sobre MarkDown

### ISSUE THREAD

**Issue by vrivas** [vrivas/git-init-uja-resrepo#7]
Acabo de acordarme, así que lo pongo aquí para que no se me olvide: hay que buscar también recursos sobre el formato Markdown.

**Comment by vrivas** [comment]
Sería interesante que también hubiera una etiqueta llamada markdown, lo mismo que están local, remoto, etc.

**Comment by josean0902** [comment]
Vale perfecto, los idiomas los pongo con siglas del estilo es (castellano),
en (inglés) o lo pongo completo?
